{
 "title": "Hardware Info",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"CPU\")\n  |> filter(fn: (r) => r._field == \"usage\")"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"GPU\")\n  |> filter(fn: (r) => r._field == \"usage\")"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"RAM\")\n  |> filter(fn: (r) => r._field == \"usage\")"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"CPU\")\n  |> filter(fn: (r) => r._field == \"temp\")"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 10, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"GPU\" and (r._field == \"temp_edge\" or r._field == \"temp_junction\" or r._field == \"temp_mem\"))"
    }
   ]
  },
  {
   "title": "CPU Power",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"CPU\")\n  |> filter(fn: (r) => r._field == \"power\")"
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 10, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"home\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r._measurement == \"GPU\")\n  |> filter(fn: (r) => r._field == \"power\")"
    }
   ]
  }
 ]
}